FROM docker.io/nousresearch/hermes-agent:latest

ENV HERMES_DASHBOARD=1
ENV HERMES_DASHBOARD_PORT=10000
ENV HERMES_DASHBOARD_BASIC_AUTH_USERNAME=hermes
ENV HERMES_DASHBOARD_BASIC_AUTH_PASSWORD=hermes123

EXPOSE 10000

CMD ["sleep", "infinity"]
